### ISSUE TITLE
Add missing transition property

### ISSUE THREAD

**Issue by tobiasroeder** [tobiasroeder/ImageBox#17]
```css
#imagebox .ib-content .ib-image-wrapper img.ib-image {
  transition: **opacity** ease-in-out .6s
}
```
